- template:
    src: nginx-proxy.template
    dest: "./cache/{{app_name}}/k8s/nginx-proxy.template"
- name: Deploy secret with nginx proxy template
  shell: >
    kubectl create secret generic nginx-proxy-cfg-template \
    --from-file="./cache/{{app_name}}/k8s/nginx-proxy.template"
  ignore_errors: yes
